-- =====================================================
-- MyLog Database Schema
-- Generated from JPA Entity Classes
-- Database: articlegreSQL
-- =====================================================

-- =====================================================
-- DROP TABLES (Reverse dependency order)
-- =====================================================

DROP TABLE IF EXISTS member_custom_style CASCADE;
DROP TABLE IF EXISTS article_ai_analyze CASCADE;
DROP TABLE IF EXISTS notification_setting CASCADE;
DROP TABLE IF EXISTS notification CASCADE;
DROP TABLE IF EXISTS comment CASCADE;
DROP TABLE IF EXISTS article_tag CASCADE;
DROP TABLE IF EXISTS tag CASCADE;
DROP TABLE IF EXISTS article CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS member CASCADE;

-- =====================================================
-- ENUM Types (articlegreSQL)
-- =====================================================

-- OauthProvider enum: LOCAL, SOCIAL, GOOGLE, KAKAO, NAVER
-- AiAnalyzeStatus enum: PENDING, COMPLETED, FAILED
-- Note: Using VARCHAR with CHECK constraint instead of ENUM for flexibility

-- =====================================================
-- CREATE TABLES
-- =====================================================

-- -----------------------------------------------------
-- Table: member
-- 사용자 계정 정보 (OAuth2 인증 지원)
-- -----------------------------------------------------
CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(30),
    password VARCHAR(150),
    member_name VARCHAR(30) NOT NULL,
    nickname VARCHAR(100) UNIQUE,
    profile_img VARCHAR(300) NOT NULL,
    bio VARCHAR(200),
    provider VARCHAR(20) NOT NULL CHECK (provider IN ('LOCAL', 'SOCIAL', 'GOOGLE', 'KAKAO', 'NAVER')),
    provider_id VARCHAR(200),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- Index for OAuth provider + provider_id unique constraint
CREATE UNIQUE INDEX idx_provider_providerId ON member (provider, provider_id);

-- -----------------------------------------------------
-- Table: category
-- 사용자 정의 카테고리
-- -----------------------------------------------------
CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(12),
    member_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- -----------------------------------------------------
-- Table: article
-- 블로그 게시글
-- -----------------------------------------------------
CREATE TABLE article (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    category_id BIGINT,
    title VARCHAR(30) NOT NULL,
    content VARCHAR(3000) NOT NULL,
    article_img VARCHAR(300),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- -----------------------------------------------------
-- Table: tag
-- 태그 (게시글 분류용)
-- -----------------------------------------------------
CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name VARCHAR(10) UNIQUE,
    created_at DATE DEFAULT CURRENT_DATE
);

-- -----------------------------------------------------
-- Table: article_tag
-- 게시글-태그 연결 테이블 (Many-to-Many)
-- -----------------------------------------------------
CREATE TABLE article_tag (
    article_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (article_id, tag_id)
);

-- -----------------------------------------------------
-- Table: comment
-- 댓글 (계층형 구조 지원)
-- -----------------------------------------------------
CREATE TABLE comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    parent_id BIGINT DEFAULT 0,
    content VARCHAR(200),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- -----------------------------------------------------
-- Table: notification
-- 사용자 알림
-- -----------------------------------------------------
CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    related_id BIGINT NOT NULL,
    read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------
-- Table: notification_setting
-- 알림 설정
-- -----------------------------------------------------
CREATE TABLE notification_setting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    disabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------
-- Table: article_ai_analyze
-- 게시글 AI 분석 결과
-- -----------------------------------------------------
CREATE TABLE article_ai_analyze (
    article_id BIGINT PRIMARY KEY,
    article_id BIGINT UNIQUE NOT NULL,
    summary TEXT,
    analyze_status VARCHAR(20) NOT NULL CHECK (analyze_status IN ('PENDING', 'COMPLETED', 'FAILED')),
    raw_response TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE
);

-- -----------------------------------------------------
-- Table: member_custom_style
-- 사용자 커스텀 스타일 설정
-- -----------------------------------------------------
CREATE TABLE member_custom_style (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    style_name VARCHAR(255) NOT NULL,
    instruction TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- =====================================================
-- FOREIGN KEY CONSTRAINTS
-- =====================================================

-- category -> member
ALTER TABLE category
    ADD CONSTRAINT fk_category_member
    FOREIGN KEY (member_id) REFERENCES member(id);

-- article -> member
ALTER TABLE article
    ADD CONSTRAINT fk_article_member
    FOREIGN KEY (member_id) REFERENCES member(id);

-- article -> category
ALTER TABLE article
    ADD CONSTRAINT fk_article_category
    FOREIGN KEY (category_id) REFERENCES category(id);

-- article_tag -> article (CASCADE DELETE)
ALTER TABLE article_tag
    ADD CONSTRAINT fk_articletag_article
    FOREIGN KEY (article_id) REFERENCES article(id) ON DELETE CASCADE;

-- article_tag -> tag
ALTER TABLE article_tag
    ADD CONSTRAINT fk_articletag_tag
    FOREIGN KEY (tag_id) REFERENCES tag(id);

-- comment -> article
ALTER TABLE comment
    ADD CONSTRAINT fk_comment_article
    FOREIGN KEY (article_id) REFERENCES article(id);

-- comment -> member
ALTER TABLE comment
    ADD CONSTRAINT fk_comment_member
    FOREIGN KEY (member_id) REFERENCES member(id);

-- notification -> member
ALTER TABLE notification
    ADD CONSTRAINT fk_notification_member
    FOREIGN KEY (member_id) REFERENCES member(id);

-- notification_setting -> member
ALTER TABLE notification_setting
    ADD CONSTRAINT fk_notification_setting_member
    FOREIGN KEY (member_id) REFERENCES member(id);

-- article_ai_analyze -> article (CASCADE DELETE)
ALTER TABLE article_ai_analyze
    ADD CONSTRAINT fk_article_ai_analyze_article
    FOREIGN KEY (article_id) REFERENCES article(id) ON DELETE CASCADE;

-- member_custom_style -> member
ALTER TABLE member_custom_style
    ADD CONSTRAINT fk_member_custom_style_member
    FOREIGN KEY (member_id) REFERENCES member(id);

-- =====================================================
-- INDEXES for Performance Optimization
-- =====================================================

-- Article 조회 최적화
CREATE INDEX idx_article_member_id ON article(member_id);
CREATE INDEX idx_article_category_id ON article(category_id);
CREATE INDEX idx_article_created_at ON article(created_at DESC);

-- Comment 조회 최적화
CREATE INDEX idx_comment_article_id ON comment(article_id);
CREATE INDEX idx_comment_member_id ON comment(member_id);
CREATE INDEX idx_comment_parent_id ON comment(parent_id);

-- Notification 조회 최적화
CREATE INDEX idx_notification_member_id ON notification(member_id);
CREATE INDEX idx_notification_created_at ON notification(created_at DESC);

-- Category 조회 최적화
CREATE INDEX idx_category_member_id ON category(member_id);

-- Tag 검색 최적화
CREATE INDEX idx_tag_name ON tag(tag_name);

-- ArticleTag 조회 최적화
CREATE INDEX idx_articletag_tag_id ON article_tag(tag_id);

-- MemberCustomStyle 조회 최적화
CREATE INDEX idx_member_custom_style_member_id ON member_custom_style(member_id);

-- =====================================================
-- COMMENTS for Documentation
-- =====================================================

COMMENT ON TABLE member IS '사용자 계정 정보 (OAuth2: Google, Kakao, Naver 지원)';
COMMENT ON TABLE category IS '사용자 정의 게시글 카테고리';
COMMENT ON TABLE article IS '블로그 게시글';
COMMENT ON TABLE tag IS '게시글 태그';
COMMENT ON TABLE article_tag IS '게시글-태그 연결 테이블 (Many-to-Many)';
COMMENT ON TABLE comment IS '계층형 댓글 (parent_id로 대댓글 지원)';
COMMENT ON TABLE notification IS '사용자 알림 (댓글, 좋아요 등)';
COMMENT ON TABLE notification_setting IS '알림 타입별 설정';
COMMENT ON TABLE article_ai_analyze IS '게시글 AI 분석 결과 저장';
COMMENT ON TABLE member_custom_style IS '사용자 커스텀 스타일 설정';

COMMENT ON COLUMN member.provider IS 'OAuth 제공자: LOCAL, SOCIAL, GOOGLE, KAKAO, NAVER';
COMMENT ON COLUMN comment.parent_id IS '부모 댓글 ID (0이면 최상위 댓글)';
COMMENT ON COLUMN article_ai_analyze.analyze_status IS '분석 상태: PENDING, COMPLETED, FAILED';
