services:
  mylog-app:
    container_name: mylog-app
    image: ${DOCKER_USERNAME}/mylog:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=${DB_URL}
      - DB_USER_NAME=${DB_USER_NAME}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - SENTRY_DSN=${SENTRY_DSN}
      - REDIRECT_URI=${REDIRECT_URI}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mylog-network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"
    depends_on:
      redis:
        condition: service_healthy
    restart: always

  mylog-app-blue:
    image: ${DOCKER_USERNAME}/mylog:latest
    container_name: mylog-app-blue
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=${DB_URL}
      - DB_USER_NAME=${DB_USER_NAME}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - SENTRY_DSN=${SENTRY_DSN}
      - REDIRECT_URI=${REDIRECT_URI}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mylog-network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis: # redis
    image: redis:8.0.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --port 6379
    networks:
      - mylog-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mylog-network:
    driver: bridge

volumes:
  redis-data:
