spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: mypassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update #자동생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

jwt:
  access_secret: ${ACCESS_TOKEN_SECRET}
  access_expiration: 86400000  # 1hours
  refresh_secret: ${REFRESH_TOKEN_SECRET}
  refresh_expiration: 604800000 #1주

oauth2:
  client:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: ${REDIRECT_URI}
    naver:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}
      redirect-uri: ${REDIRECT_URI}
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      redirect-uri: ${REDIRECT_URI}

sentry:
  dsn: ${SENTRY_DSN}
  environment: development

# aws.s3.bucket
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: mylog-imgsource
      basic: https://mylog-imgsource.s3.ap-northeast-2.amazonaws.com/5162d5b3-266b-4aae-bc16-d7f10fc4b2f1_basic.png


management:
  endpoints:
    web:
      exposure:
        include: "*"