spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update #자동생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

#jwt:
#  secret:
#  expiration: 86400000 # 24 hours in milliseconds
#
#oauth2:
#  client:
#    google:
#      client-id: ${GOOGLE_CLIENT_ID_DEV}
#      client-secret: ${GOOGLE_CLIENT_SECRET_DEV}
#      redirect-uri: http://localhost:8080/api/login/oauth2/code/google
#    github:
#      client-id: ${GITHUB_CLIENT_ID_DEV}
#      client-secret: ${GITHUB_CLIENT_SECRET_DEV}
#      redirect-uri: http://localhost:8080/api/login/oauth2/code/github
#
#sentry:
#  dsn: ${SENTRY_DSN_DEV}
#  environment: development
#
#aws:
#  s3:
#    bucket: ${AWS_S3_BUCKET_DEV}
#    region: ${AWS_REGION:us-east-1}
#    credentials:
#      access-key: ${AWS_ACCESS_KEY_DEV}
#      secret-key: ${AWS_SECRET_KEY_DEV}
