spring:
  profiles:
    active: prod

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /api-docs

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG