spring:
  datasource:
    url: ${}
    driver-class-name: org.postgresql.Driver
    username: ${}
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

jwt:
  access_secret: ${ACCESS_TOKEN_SECRET}
  access_expiration: 30  # 1hours
  refresh_secret: ${REFRESH_TOKEN_SECRET}
  refresh_expiration: 7 #1주


oauth2:
  client:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: http://localhost:3000
    naver:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}
      redirect-uri: http://localhost:3000
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      redirect-uri: http://localhost:3000



#oauth2:
#  client:
#    google:
#      client-id: ${GOOGLE_CLIENT_ID_PROD}
#      client-secret: ${GOOGLE_CLIENT_SECRET_PROD}
#      redirect-uri: https://your-domain.com/api/login/oauth2/code/google
#    github:
#      client-id: ${GITHUB_CLIENT_ID_PROD}
#      client-secret: ${GITHUB_CLIENT_SECRET_PROD}
#      redirect-uri: https://your-domain.com/api/login/oauth2/code/github
#
#sentry:
#  dsn: ${SENTRY_DSN_PROD}
#  environment: production
#
#aws:
#  s3:
#    bucket: ${AWS_S3_BUCKET_PROD}
#    region: ${AWS_REGION:us-east-1}
#    credentials:
#      access-key: ${AWS_ACCESS_KEY_PROD}
#      secret-key: ${AWS_SECRET_KEY_PROD}